---
# Docker Configuration for GPU Nodes
docker_config:
  default-runtime: "nvidia"
  runtimes:
    nvidia:
      path: "/usr/bin/nvidia-container-runtime"
      runtimeArgs: []
  exec-opts:
    - "native.cgroupdriver=systemd"
  log-driver: "json-file"
  log-opts:
    max-size: "200m"
    max-file: "5"
  storage-driver: "overlay2"

# Kubelet Configuration for GPU Nodes
kubelet_flags:
  - "--container-runtime=remote"
  - "--container-runtime-endpoint=unix:///var/run/dockershim.sock"  # Change if using Containerd
  - "--feature-gates=DevicePlugins=true"
  - "--node-labels=nvidia.com/gpu=true"
  - "--register-with-taints=nvidia.com/gpu=true:NoSchedule"

# NVIDIA Specific Settings
nvidia:
  runtime_class: "nvidia"
  device_plugin_version: "v0.14.1"
  mig_strategy: "none"  # Options: none, single, mixed

# NVIDIA Device Plugin Image (Updated)
nvidia_device_plugin:
  image: "nvcr.io/nvidia/k8s-device-plugin:v0.14.1"

# Validation commands (commented as documentation)
# docker_config_validation: "sudo docker daemon --validate --config-file=/etc/docker/daemon.json"
# docker_dry_run: "sudo dockerd --config-file=/etc/docker/daemon.json --dry-run"
# containerd_config_validation: "sudo containerd config validate"
# containerd_dry_run: "sudo containerd --config /etc/containerd/config.toml --state /run/containerd"

nvidia_container_runtime_enabled: true
nvidia_mig:
  enabled: false
  profiles: []