# group_vars/k8s-cluster.yml
---
# Kubernetes cluster configuration
k8s_version: "1.28.0"
pod_network_cidr: "192.168.1.0/24"  # Class C network
service_cidr: "192.168.2.0/24"       # Class C network
cluster_name: "k8s-cluster"

# DNS Configuration
cluster_dns:
  primary: "{{ (service_cidr|ipaddr('network'))|ipaddr('+10') }}"  # CoreDNS IP (10th address)
  secondary: "172.20.1.3"                                           # Fallback DNS
  internal: 
    - ".svc"
    - ".svc.cluster.local"

# Docker Network Integration
docker_network:
  bip: "{{ (pod_network_cidr|ipaddr('first_usable'))|ipaddr('+1')|ipaddr('net') }}"
  mtu: null
  no_proxy: "{{ [service_cidr, pod_network_cidr] + cluster_dns.internal|list }}"