# roles/kubernetes/vars/main.yml
---
# Kubernetes Core Components
# 📌 Version-Pinned Components
k8s:
  version: "1.28.0"
  components:
    - kubelet
    - kubeadm
    - kubectl
    - cri-tools
  # Repository Configuration  
  repo: 
    ubuntu:
      gpg_key: "https://pkgs.k8s.io/core:/stable:/v{{ k8s_version.split('.')[0:2] | join('.') }}/deb/Release.key"
      repo_url: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ k8s_version.split('.')[0:2] | join('.') }}/deb/ /"
    rocky:
      gpg_key: "https://pkgs.k8s.io/core:/stable:/v{{ k8s_version.split('.')[0:2] | join('.') }}/rpm/repodata/repomd.xml.key"
      repo_url: "https://pkgs.k8s.io/core:/stable:/v{{ k8s_version.split('.')[0:2] | join('.') }}/rpm/"

# Sys 
  # OS-Specific Package Names
  packages:
    ubuntu:
      kubelet: "kubelet={{ k8s_version }}-*"
      kubeadm: "kubeadm={{ k8s_version }}-*"
      kubectl: "kubectl={{ k8s_version }}-*"
    rocky:
      kubelet: "kubelet-{{ k8s_version }}-*"
      kubeadm: "kubeadm-{{ k8s_version }}-*"
      kubectl: "kubectl-{{ k8s_version }}-*"  


# Networking Configuration
pod_network_cidr: "192.168.1.0/24"
service_cidr: "192.168.2.0/24"
dns_domain: "cluster.local"
network_plugin: "flannel"  # Options: flannel, calico, cilium, weave

# Cluster Initialization
kubeadm_init_flags:
  - "--pod-network-cidr={{ pod_network_cidr }}"
  - "--service-cidr={{ service_cidr }}"
  - "--ignore-preflight-errors=Swap"
  - "--upload-certs"

# Container Runtime Configuration
container_runtime: "containerd"
cri_socket: "/run/containerd/containerd.sock"


# System Configuration
kubelet_flags:
  - "--container-runtime=remote"
  - "--container-runtime-endpoint=unix://{{ cri_socket }}"
  - "--node-ip=$(hostname -I | awk '{print $1}')"

# Addon Configuration
cni_plugins:
  flannel:
    manifest: "https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml"
    requirements: []
  calico:
    manifest: "https://docs.projectcalico.org/manifests/calico.yaml"
    requirements:
      - "ipset"
      - "iptables"

# 🌐 Network Configuration
cni:
  plugin: "calico"
  cidr: "192.168.2.0/24"
  version: "3.26.0"

# Security
enforce_node_restrictions: true
allow_privileged: false
protect_kernel_defaults: true

# Resource Limits
kubelet_reserved:
  cpu: "500m"
  memory: "500Mi"
  ephemeral-storage: "1Gi"
system_reserved:
  cpu: "500m"
  memory: "500Mi"
  ephemeral-storage: "1Gi"

  # Add these new variables:
kubelet_extra_args:
  - "--node-ip=$(hostname -I | awk '{print $1}')"
  - "--pod-cidr={{pod_network_cidr}}"
  - "--feature-gates=DevicePlugins=true"
  - "--allowed-unsafe-sysctls=net.core.somaxconn"
  - "--protect-kernel-defaults=true"
  - "--read-only-port=0"
# Enhanced network plugin configuration
network_plugins:
  flannel:
    manifest: "https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml"
    requirements: []
    config: |
      {
        "Network": "{{ pod_network_cidr }}",
        "Backend": {"Type": "vxlan"}
      }
  calico:
    manifest: "https://docs.projectcalico.org/manifests/calico.yaml"
    requirements:
      - "ipset"
      - "iptables"

containerd_config:
  version = 2
  [plugins."io.containerd.grpc.v1.cri"]
    sandbox_image = "registry.k8s.io/pause:3.8"