# roles/nvidia/defaults/main.yml
---
# NVIDIA Driver Configuration
nvidia_driver_version: "550"
cuda_version: "12.4"

# Package Configuration
nvidia_driver_packages:
  ubuntu:
    - "nvidia-driver-{{ nvidia_driver_version }}"
    - "nvidia-dkms-{{ nvidia_driver_version }}"
    - "nvidia-utils-{{ nvidia_driver_version }}"
    - "cuda-{{ cuda_version | replace('.', '-') }}"
  rocky:
    - "nvidia-driver-{{ nvidia_driver_version }}.*"
    - "kernel-devel-{{ ansible_kernel }}"
    - "cuda-toolkit-{{ cuda_version | replace('.', '-') | truncate(3, True, '') }}"

# Container Runtime Configuration
nvidia_container_toolkit_version: "v1.14.6"
nvidia_runtime_name: "nvidia"
nvidia_runtime_path: "/usr/bin/nvidia-container-runtime"
nvidia_runtime_class: "nvidia"
nvidia_set_as_default: true

# Runtime Options
nvidia_runtime_options:
  Runtime: "containerd"  # Options: containerd, docker
  SystemdCgroup: true
  Debug: false

# Kubernetes Integration
nvidia_device_plugin:
  enabled: true
  image: "nvcr.io/nvidia/k8s-device-plugin:v0.14.1"
  args: ["--mig-strategy=none"]
  resources:
    limits:
      nvidia.com/gpu: 1

# MIG Configuration
nvidia_mig:
  enabled: false
  profiles: []
  
nvidia_gpu_types:
  a100:
    mig_profiles:
      - "1g.5gb"
      - "2g.10gb"
  h100:
    mig_profiles:
      - "1g.10gb"
      - "2g.20gb"

# Monitoring Configuration
nvidia_dcgm:
  enabled: false
  version: "3.3.1"
  
nvidia_dcgm_exporter:
  enabled: true
  config:
    port: 9400
    metrics:
      - "DCGM_FI_DEV_GPU_UTIL"
      - "DCGM_FI_DEV_MEM_COPY_UTIL"

# Feature Gates
nvidia_feature_gates:
  - "DevicePlugins=true"
  - "MixedCPUsAllocation=true"

# Resource Allocation
nvidia_compute_resources:
  nvidia.com/gpu: 8