# roles/nvidia/tasks/install.yml
---
- name: Install NVIDIA packages (Ubuntu)
  apt:
    name:
      - nvidia-driver-{{ nvidia_driver_version }}
      - nvidia-dkms-{{ nvidia_driver_version }}
      - nvidia-utils-{{ nvidia_driver_version }}
      - nvidia-container-toolkit
      - nvidia-container-runtime
      - kernel-devel-{{ ansible_kernel }}  # Added kernel tools
    state: present
  when: ansible_distribution == 'Ubuntu'
  tags: [nvidia, install]

- name: Install NVIDIA packages (Rocky)
  yum:
    name:
      - nvidia-driver-{{ nvidia_driver_version }}.*
      - nvidia-container-toolkit
      - nvidia-container-runtime
      - kernel-devel-{{ ansible_kernel }}  # Required for DKMS
      - gcc
      - make
    enablerepo: nvidia-container-toolkit
    state: present
  when: ansible_distribution == 'Rocky'
  tags: [nvidia, install]