# roles/nvidia/vars/main.yml
---
- name: Verify NVIDIA hardware
  command: lspci | grep -i nvidia
  register: nvidia_hw
  changed_when: false
  tags: [nvidia, verify]

- name: Add NVIDIA repository
  include_tasks: repos.yml
  when: nvidia_hw.stdout != ""
  tags: [nvidia, repos]

- name: Install NVIDIA drivers
  include_tasks: drivers.yml
  when: nvidia_hw.stdout != ""
  tags: [nvidia, drivers]

- name: Configure container runtime
  include_tasks: runtime.yml
  when: nvidia_hw.stdout != ""
  tags: [nvidia, runtime]

- name: Enable MIG (if configured)
  include_tasks: mig.yml
  when: 
    - nvidia_hw.stdout != ""
    - nvidia_mig.enabled | default(false) | bool
  tags: [nvidia, mig]

- name: Validate NVIDIA setup
  include_tasks: validate.yml
  when: nvidia_hw.stdout != ""
  tags: [nvidia, validate]
  