# roles/nvidia/tasks/main.yml
---
- name: Verify NVIDIA hardware
  command: lspci | grep -i nvidia
  register: nvidia_hw
  changed_when: false
  tags: [nvidia, verify]

- name: Add NVIDIA repository
  include_tasks: repos.yml
  when: 
    - nvidia_hw.stdout != ""
    - not ansible_check_mode
  tags: [nvidia, repos]

- name: Install NVIDIA components
  include_tasks: install.yml  # Now includes both drivers and toolkit
  when: nvidia_hw.stdout != ""
  tags: [nvidia, install]

- name: Configure container runtime
  include_tasks: runtime.yml
  when: 
    - nvidia_hw.stdout != ""
    - nvidia_container_runtime_enabled | default(true) | bool
  tags: [nvidia, runtime]

- name: Enable MIG (if configured)
  include_tasks: mig.yml
  when: 
    - nvidia_hw.stdout != ""
    - nvidia_mig.enabled | default(false) | bool
  tags: [nvidia, mig]

- name: Validate NVIDIA setup
  include_tasks: validate.yml
  when: nvidia_hw.stdout != ""
  tags: [nvidia, validate]