# roles/nvidia/tasks/mig.yml

---
- name: Detect GPU model
  command: nvidia-smi --query-gpu=gpu_name --format=csv,noheader
  register: gpu_model
  changed_when: false

- name: Enable MIG mode
  command: nvidia-smi -mig 1
  when: "'A100' in gpu_model.stdout or 'H100' in gpu_model.stdout"

- name: Configure MIG profiles
  command: nvidia-smi mig -cgi "{{ item }}"
  with_items: "{{ nvidia_gpu_types[gpu_model.stdout | lower].mig_profiles }}"
  when: "'A100' in gpu_model.stdout or 'H100' in gpu_model.stdout"