---
- name: Verify NVIDIA toolkit installation
  command: nvidia-container-toolkit --version
  register: toolkit_check
  changed_when: false
  failed_when: toolkit_check.rc != 0
  tags: [nvidia, runtime]

- name: Ensure containerd config directory exists
  file:
    path: /etc/containerd
    state: directory
    mode: 0755
  tags: [nvidia, runtime]

- name: Configure containerd for NVIDIA
  blockinfile:
    path: /etc/containerd/config.toml
    marker: "# {mark} ANSIBLE MANAGED BLOCK - NVIDIA RUNTIME"
    block: |
      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia]
        runtime_type = "io.containerd.runc.v2"
        privileged_without_host_devices = false
        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia.options]
          BinaryName = "{{ nvidia_runtime_path }}"
          SystemdCgroup = {{ nvidia_runtime_options.SystemdCgroup | lower }}
  notify: restart containerd
  when: toolkit_check.rc == 0
  tags: [nvidia, runtime]

- name: Set default runtime to NVIDIA (if configured)
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^(\s*)default_runtime_name\s*='
    line: '\1default_runtime_name = "{{ nvidia_runtime_name }}"'
    insertafter: '\[plugins\."io\.containerd\.grpc\.v1\.cri"\.containerd\]'
  notify: restart containerd
  when: 
    - toolkit_check.rc == 0
    - nvidia_runtime_options.Runtime == "containerd"
  tags: [nvidia, runtime]

- name: Validate containerd config
  command: containerd config validate /etc/containerd/config.toml
  register: containerd_validate
  changed_when: false