
# role/tasks/runtime.yml
---
- name: Verify NVIDIA toolkit installation
  command: nvidia-container-toolkit --version
  register: toolkit_check
  changed_when: false
  failed_when: toolkit_check.rc != 0
  tags: [nvidia, runtime]

- name: Configure container runtime (Docker)
  block:
    - name: Ensure Docker config directory exists
      file:
        path: /etc/docker
        state: directory
        mode: 0755
      when: nvidia_runtime_options.Runtime == "docker"

    - name: Configure Docker for NVIDIA
      template:
        src: etc/docker/daemon-nvidia.json.j2
        dest: "{{ docker_config_file | default('/etc/docker/daemon.json') }}"
        owner: root
        group: root
        mode: 0644
      notify: restart docker
      when: nvidia_runtime_options.Runtime == "docker"
  when: toolkit_check.rc == 0
  tags: [nvidia, runtime]

- name: Configure container runtime (containerd)
  block:
    - name: Ensure containerd config directory exists
      file:
        path: /etc/containerd
        state: directory
        mode: 0755
      when: nvidia_runtime_options.Runtime == "containerd"

    - name: Configure containerd for NVIDIA
      blockinfile:
        path: /etc/containerd/config.toml
        marker: "# {mark} ANSIBLE MANAGED BLOCK - NVIDIA RUNTIME"
        block: |
          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia]
            runtime_type = "io.containerd.runc.v2"
            privileged_without_host_devices = false
            [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia.options]
              BinaryName = "{{ nvidia_runtime_path }}"
              SystemdCgroup = {{ nvidia_runtime_options.SystemdCgroup | lower }}
      notify: restart containerd
      when: nvidia_runtime_options.Runtime == "containerd"

    - name: Set default runtime to NVIDIA (containerd only)
      lineinfile:
        path: /etc/containerd/config.toml
        regexp: '^(\s*)default_runtime_name\s*='
        line: '\1default_runtime_name = "{{ nvidia_runtime_name }}"'
        insertafter: '\[plugins\."io\.containerd\.grpc\.v1\.cri"\.containerd\]'
      notify: restart containerd
      when:
        - nvidia_runtime_options.Runtime == "containerd"
        - nvidia_set_as_default | default(true) | bool
  when: toolkit_check.rc == 0
  tags: [nvidia, runtime]

- name: Validate runtime configuration
  block:
    - name: Validate Docker config (if using Docker)
      command: docker config validate {{ docker_config_file | default('/etc/docker/daemon.json') }}
      when: nvidia_runtime_options.Runtime == "docker"
      register: docker_validate

    - name: Validate containerd config (if using containerd)
      command: containerd config validate /etc/containerd/config.toml
      when: nvidia_runtime_options.Runtime == "containerd"
      register: containerd_validate

    - name: Show validation summary
      debug:
        msg: |
          Runtime: {{ nvidia_runtime_options.Runtime }}
          Docker Valid: {{ docker_validate is defined and docker_validate.rc == 0 }}
          Containerd Valid: {{ containerd_validate is defined and containerd_validate.rc == 0 }}
  tags: [nvidia, validation]