# roles/nvidia/tasks/validate.yml
---
- name: Verify Kubernetes GPU support
  command: kubectl get nodes -o jsonpath='{.items[*].status.allocatable.nvidia\.com/gpu}'
  register: k8s_gpu
  changed_when: false

- name: Verify MIG configuration
  command: nvidia-smi mig -lgi
  when: nvidia_mig_enabled | bool
  register: mig_status
  changed_when: false

- name: Show validation summary
  debug:
    msg: |
      Kubernetes GPU Allocation: {{ k8s_gpu.stdout }}
      MIG Status: {{ mig_status.stdout if mig_status is defined else 'Disabled' }}
      Driver Version: {{ nvidia_smi.stdout_lines[2] }}