# roles/container/tasks/configure.yml

---
- name: Configure container runtime (NVIDIA or default)
  template:
    src: "{{ 'daemon.nvidia.json.j2' if has_nvidia | default(false) else 'daemon.docker.json.j2' }}"
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
  when: container_runtime == 'docker'
  notify: restart docker

- name: Load kernel modules (overlay, br_netfilter)
  ansible.builtin.shell: "modprobe {{ item }}"
  loop:
    - overlay
    - br_netfilter

# Only needed if you plan to reboot the host later
- name: Persist kernel modules across reboots
  copy:
    dest: /etc/modules-load.d/container.conf
    content: |
      overlay
      br_netfilter
    mode: '0644'
