# roles/container/tasks/configure.yml

---
- name: Configure container runtime
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  when: container_runtime == 'docker'
  notify: restart docker

- name: Load kernel modules (overlay, br_netfilter)
  ansible.builtin.shell: "modprobe {{ item }}"
  loop:
    - overlay
    - br_netfilter
  become: true

# Only needed if you plan to reboot the host later
- name: Persist kernel modules across reboots
  copy:
    dest: /etc/modules-load.d/container.conf
    content: |
      overlay
      br_netfilter
    mode: '0644'
  become: true
