---
# roles/container/tasks/configure.yml

- name: Ensure Docker data-root directory exists
  file:
    path: /tmp/docker
    state: directory
    owner: root
    group: root
    mode: '0711'
  when: container_runtime == 'docker'

- name: Configure container runtime (NVIDIA or default)
  template:
    src: "{{ 'daemon.nvidia.json.j2' if has_nvidia | default(false) else 'daemon.docker.json.j2' }}"
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
  when: container_runtime == 'docker'
  notify: "🔄 Restart Docker"

- name: Load kernel modules (overlay, br_netfilter)
  ansible.builtin.shell: "modprobe {{ item }}"
  loop:
    - overlay
    - br_netfilter
  become: true

- name: Persist kernel modules across reboots
  copy:
    dest: /etc/modules-load.d/container.conf
    content: |
      overlay
      br_netfilter
    owner: root
    group: root
    mode: '0644'
  become: true
