# roles/container/tasks/install.yml
---
- name: Update package cache (Rocky only)
  dnf:
    update_cache: yes
  when: ansible_distribution == "Rocky"

- name: Add Docker repository
  shell: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo
  when: ansible_distribution == "Rocky"

- name: Install Docker (Rocky and Ubuntu)
  package:
    name: "{{ docker_packages }}"
    state: present

# Note: docker_packages is set earlier via set_fact in main.yml

- name: Enable and start Docker service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Add user to Docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
