# roles/container/tasks/install.yml
---
- name: Update DNF cache (Rocky only)
  dnf:
    update_cache: yes
  when: ansible_distribution == "Rocky"

- name: Install dnf-utils for repo management
  package:
    name: dnf-utils
    state: present
  when: ansible_distribution == "Rocky"

- name: Add Docker repository for Rocky
  shell: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo
  when: ansible_distribution == "Rocky"

- name: Clean DNF metadata
  shell: dnf clean all && dnf makecache
  when: ansible_distribution == "Rocky"

- name: Install Docker packages
  package:
    name: "{{ docker_packages }}"
    state: present

- name: Enable and start Docker
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Add user to Docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
