# roles/container/tasks/install.yml
---
- name: Update DNF cache (Rocky only)
  dnf:
    update_cache: yes
  when: ansible_distribution == "Rocky"

- name: Install dnf-utils for repo management
  package:
    name: dnf-utils
    state: present
  when: ansible_distribution == "Rocky"

- name: Add Docker repository for Rocky
  ansible.builtin.shell: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo
  when: ansible_distribution == "Rocky"

- name: Import Docker GPG key (optional but recommended)
  rpm_key:
    state: present
    key: https://download.docker.com/linux/centos/gpg
  when: ansible_distribution == "Rocky"

- name: Clean DNF metadata
  shell: dnf clean all && dnf makecache
  when: ansible_distribution == "Rocky"

- name: Verify docker-ce is available before install
  shell: dnf list docker-ce docker-ce-cli containerd.io
  register: docker_check
  failed_when: docker_check.rc != 0
  changed_when: false
  when: ansible_distribution == "Rocky"

- name: Install Docker packages
  package:
    name: "{{ docker_packages }}"
    state: present
  check_mode: no
  register: docker_pkg_result
  changed_when: docker_pkg_result is changed

- name: Show Docker install result
  debug:
    var: docker_pkg_result

- name: Enable and start Docker
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Add user to Docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  tags: install

# sudo usermod -aG docker $USER
# newgrp docker

