# roles/container/tasks/nvidia.yml
#
---

# NVIDIA repository setup and toolkit installation
- name: Configure NVIDIA repository
  shell: |
    curl -s -L https://nvidia.github.io/libnvidia-container/stable/rpm/nvidia-container-toolkit.repo | tee /etc/yum.repos.d/nvidia-container-toolkit.repo
    sudo rpm --import https://nvidia.github.io/nvidia-container-runtime/gpgkey
    dnf clean all && dnf makecache
  tags: [gpu, nvidia]

- name: Verify NVIDIA Container Toolkit availability
  shell: dnf list nvidia-container-toolkit
  register: nvidia_check
  failed_when: nvidia_check.rc != 0

- name: Install NVIDIA Container Toolkit and configure Docker
  block:
    - name: Remove conflicting NVIDIA packages
      dnf:
        name: cm-nvidia-container-toolkit
        state: absent
      ignore_errors: yes  # Ignore if not installed or other errors

    - name: Remove conflicting Docker packages
      package:
        name: cm-docker
        state: absent
      ignore_errors: true

    - name: Install NVIDIA Container Toolkit packages
      dnf:
        name: nvidia-container-toolkit
        state: present
        # Force the installation by overriding potential conflicts
        # This ensures the toolkit is installed and any conflicts are resolved
        # during the installation process.
        enablerepo: nvidia-container-toolkit
        install_weak_deps: false

    - name: Configure Docker for NVIDIA
      shell: |
        nvidia-ctk runtime configure --runtime=docker
  tags: [gpu, nvidia]

- name: Configure NVIDIA runtime
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "runtimes": {
          "nvidia": {
            "path": "/usr/bin/nvidia-container-runtime",
            "runtimeArgs": []
          }
        },
        "default-runtime": "nvidia"
      }
  notify: restart docker
  tags: [gpu, nvidia]
