# roles/container/tasks/nvidia.yml
#
---

# NVIDIA repository setup and toolkit installation
- name: Configure NVIDIA repository
  shell: |
    curl -s -L https://nvidia.github.io/libnvidia-container/stable/rpm/nvidia-container-toolkit.repo | tee /etc/yum.repos.d/nvidia-container-toolkit.repo
    rpm --import https://nvidia.github.io/nvidia-container-runtime/gpgkey
    dnf clean all && dnf makecache
  become: true
  args:
    warn: false
  register: nvidia_repo
  tags: [nvidia, install]

- name: Check if conflicting NVIDIA or Docker packages are installed
  shell: |
    rpm -qa cm-nvidia-container-toolkit cm-docker* || true
  register: conflicting_pkgs
  changed_when: false
  failed_when: false
  tags: [nvidia, install]

- name: Remove conflicting packages if they exist
  package:
    name:
      - cm-nvidia-container-toolkit
      - cm-docker*
    state: absent
  when: >
    "'cm-nvidia-container-toolkit is not installed' not in conflicting_pkgs.stdout or
     'cm-docker is not installed' not in conflicting_pkgs.stdout"
  tags: [nvidia, install]

- name: Install NVIDIA Container Toolkit (from proper repo)
  dnf:
    name: nvidia-container-toolkit
    state: present
    enablerepo: nvidia-container-toolkit
    install_weak_deps: false
    # Force the installation by overriding potential conflicts
    # This ensures the toolkit is installed and any conflicts are resolved
    # during the installation process.
  tags: [nvidia, install]

- name: Configure Docker for NVIDIA
  shell: |
    nvidia-ctk runtime configure --runtime=docker
  when: ansible_facts['distribution'] == 'Rocky'  # or any condition to guard it
  tags: [nvidia, install]

