# roles/container/tasks/nvidia.yml
#
---

# NVIDIA repository setup and toolkit installation
- name: Configure NVIDIA repository (Rocky 8/9)
  get_url:
    url: "https://nvidia.github.io/libnvidia-container/stable/rhel{{ ansible_distribution_major_version }}/$basearch/nvidia-container-toolkit.repo"
    dest: /etc/yum.repos.d/nvidia-container-toolkit.repo
    mode: '0644'
  become: true
  tags: [nvidia, install]

- name: Import NVIDIA GPG key
  rpm_key:
    key: https://nvidia.github.io/libnvidia-container/gpgkey
    state: present
  become: true
  tags: [nvidia, install]

- name: Refresh yum cache
  command: dnf makecache
  become: true
  tags: [nvidia, install]

- name: Check if conflicting NVIDIA or Docker packages are installed
  shell: |
    rpm -qa cm-nvidia-container-toolkit cm-docker* || true
  register: conflicting_pkgs
  changed_when: false
  failed_when: false
  tags: [nvidia, install]

- name: Remove conflicting packages if they exist
  package:
    name:
      - cm-nvidia-container-toolkit
      - cm-docker*
    state: absent
  when: >
    "'cm-nvidia-container-toolkit is not installed' not in conflicting_pkgs.stdout or
     'cm-docker is not installed' not in conflicting_pkgs.stdout"
  tags: [nvidia, install]

- name: Install NVIDIA Container Toolkit (from proper repo)
  dnf:
    name: nvidia-container-toolkit
    state: present
    install_weak_deps: false
    # Force the installation by overriding potential conflicts
    # This ensures the toolkit is installed and any conflicts are resolved
    # during the installation process.
  tags: [nvidia, install]

- name: Configure Docker for NVIDIA
  shell: |
    nvidia-ctk runtime configure --runtime=docker
  when: ansible_facts['distribution'] == 'Rocky'  # or any condition to guard it
  tags: [nvidia, install]

