# roles/kubernetes/tasks/verify.yml

- name: Set kubeconfig path
  set_fact:
    kubeconfig_dir: "{{ '/root/.kube' if ansible_user == 'root' else '/home/' + ansible_user + '/.kube' }}"
  tags: verify

- name: Check kubelet status
  ansible.builtin.service:
    name: kubelet
    state: started
  tags: verify

- name: Validate kubectl cluster-info
  command: kubectl cluster-info
  register: cluster_info
  environment:
    KUBECONFIG: "{{ kubeconfig_dir }}/config"
  changed_when: false
  failed_when: cluster_info.rc != 0
  tags: verify

- name: Print kubectl cluster-info result
  debug:
    var: cluster_info.stdout_lines
  tags: verify

