# roles/kubernetes/tasks/verify.yml

- name: Set kubeconfig path
  set_fact:
    kubeconfig_dir: "{{ '/root/.kube' if ansible_user == 'root' else '/home/' + ansible_user + '/.kube' }}"
  tags: verify

- name: Check kubelet status
  ansible.builtin.service:
    name: kubelet
    state: started
  tags: verify

- name: Force override cluster server endpoint in kubeconfig (verify)
  command: >
    kubectl config set-cluster kubernetes
    --server=https://{{ k8s_api_ip }}:6443
    --kubeconfig={{ kubeconfig_dir }}/config
  when:
    - k8s_api_ip is defined
  tags: [verify]

- name: Validate kubectl cluster-info
  command: kubectl cluster-info
  register: cluster_info
  environment:
    KUBECONFIG: "{{ kubeconfig_dir }}/config"
  changed_when: false
  failed_when: cluster_info.rc != 0
  tags: verify

- name: Print kubectl cluster-info result
  debug:
    var: cluster_info.stdout_lines
  tags: verify

