---
- name: Include OS-specific tasks
  include_tasks: "{{ ansible_distribution | lower }}.yml"
  when: ansible_distribution in ['Ubuntu', 'Rocky']

- include_tasks: kernel.yml
- include_tasks: repos.yml