# roles/common/tasks/main.yml
---
- name: Include preflight checks
  include_tasks: preflight.yml
  tags: preflight

- name: Include OS-specific tasks
  block:
    - name: Load OS-specific configuration
      include_tasks: "{{ (ansible_distribution | lower) ~ '.yml' }}"
  rescue:
    - name: Fail with helpful message
      fail:
        msg: "No configuration found for {{ ansible_distribution }}. Supported OS: Ubuntu, Rocky"
  when: ansible_distribution in ['Ubuntu', 'Rocky']
  tags: os-specific

- name: Configure kernel modules
  include_tasks: kernel.yml
  tags: kernel

- name: Configure package repositories
  include_tasks: repos.yml
  tags: repos

# NEW VALIDATION TASKS ADDED HERE
- name: Validate container configurations
  block:
    - name: Validate Docker config
      command: docker config validate -f {{ docker_config_file | default('/etc/docker/daemon.json') }}
      
      when: not ansible_check_mode

    - name: Validate containerd config
      command: containerd config dump >/dev/null
      when: not ansible_check_mode
  tags: validation

- name: Configure containerd for NVIDIA
  block:
    - name: Ensure containerd config directory exists
      file:
        path: /etc/containerd
        state: directory
        mode: 0755
      tags: containerd

    - name: Deploy containerd configuration
      template:
        src: containerd-config.toml.j2
        dest: /etc/containerd/config.toml
        owner: root
        group: root
        mode: 0644
      notify: "restart containerd"
      tags: containerd
  when: 
    - "'gpu' in group_names"
    - ansible_distribution in ['Ubuntu', 'Rocky']
  tags: nvidia,containerd