---
- name: Configure Docker repository (Ubuntu)
  block:
    - name: Add Docker GPG key (Ubuntu)
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository (Ubuntu)
      apt_repository:
        repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker-ce
        update_cache: yes
  when: ansible_distribution == 'Ubuntu'
  tags: repos,docker

- name: Configure Docker repository (Rocky)
  block:
    - name: Add Docker repository (Rocky)
      yum_repository:
        name: docker-ce
        description: Docker CE Stable
        baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/centos/gpg
        enabled: yes
  when: ansible_distribution == 'Rocky'
  tags: repos,docker

- name: Configure Kubernetes repository (Ubuntu)
  block:
    - name: Add Kubernetes GPG key
      apt_key:
        url: https://pkgs.k8s.io/core:/stable:/v{{ k8s_version.split('.')[0:2] | join('.') }}/deb/Release.key
        state: present

    - name: Add Kubernetes repository
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ k8s_version.split('.')[0:2] | join('.') }}/deb/ /"
        state: present
        filename: kubernetes
        update_cache: yes
  when: ansible_distribution == 'Ubuntu'
  tags: repos,kubernetes

- name: Configure Kubernetes repository (Rocky)
  yum_repository:
    name: kubernetes
    description: Kubernetes
    baseurl: https://pkgs.k8s.io/core:/stable:/v{{ k8s_version.split('.')[0:2] | join('.') }}/rpm/
    gpgcheck: yes
    gpgkey: https://pkgs.k8s.io/core:/stable:/v{{ k8s_version.split('.')[0:2] | join('.') }}/rpm/repodata/repomd.xml.key
    enabled: yes
  when: ansible_distribution == 'Rocky'
  tags: repos,kubernetes

- name: Update package cache
  package:
    update_cache: yes
  tags: repos