# roles/common/tasks/validate.yml

---
- name: Validate Docker configuration syntax
  command: docker config validate {{ docker_config_file | default('/etc/docker/daemon.json') }}
  register: docker_validate
  changed_when: false
  failed_when: docker_validate.rc != 0
  tags: validation

- name: Test Docker daemon startup (dry-run)
  command: dockerd --validate --config-file={{ docker_config_file | default('/etc/docker/daemon.json') }}
  register: docker_dryrun
  changed_when: false
  when: not ansible_check_mode
  tags: validationgrep 