# roles/common/tasks/validate.yml

---
- name: Validate Docker config
  command: docker config validate -f {{ docker_config_file }}
  when: not ansible_check_mode

- name: Validate containerd
  command: containerd config dump >/dev/null
  when: not ansible_check_mode