# roles/docker/tasks/main.yml
---
- name: Gather OS-specific facts
  setup:
    filter: "ansible_distribution*"
  tags: [docker]

- name: Include OS-specific prerequisites
  include_tasks: "prereqs_{{ ansible_distribution | lower }}.yml"
  tags: [docker, prereqs]

- name: Install Docker components
  include_tasks: install.yml
  tags: [docker, install]

- name: Configure Docker environment
  include_tasks: config.yml
  tags: [docker, config]

- name: Manage Docker services
  include_tasks: service.yml
  tags: [docker, service]

- name: Validate Docker installation
  include_tasks: validate.yml
  tags: [docker, validate]

- name: Configure NVIDIA runtime (if enabled)
  include_tasks: nvidia.yml
  when: docker_nvidia_enabled | bool
  tags: [docker, nvidia]