# roles/docker/tasks/main.yml
---
- name: Gather OS-specific facts
  setup:
    filter: "ansible_distribution*"
  tags: [docker]

# ======================
# Installation Section
# ======================
- name: Install Docker components
  block:
    - name: Install Docker (Ubuntu)
      apt:
        name:
          - docker-ce={{ docker_version }}*
          - docker-ce-cli={{ docker_version }}*
          - containerd.io
        state: present
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'
      tags: [docker, install]

    - name: Handle Rocky Linux installation
      block:
        - name: Remove conflicting NVIDIA packages (GPU nodes only)
          block:
            - name: Check for CM-NVIDIA toolkit
              command: rpm -q cm-nvidia-container-toolkit
              register: cm_toolkit_check
              ignore_errors: yes
              changed_when: false

            - name: Purge CM-NVIDIA toolkit
              yum:
                name: cm-nvidia-container-toolkit
                state: absent
                disable_gpg_check: yes
              when: cm_toolkit_check.rc == 0
              notify: Restart Docker

        - name: Install Docker packages
          yum:
            name:
              - docker-ce-{{ docker_version }}*
              - docker-ce-cli-{{ docker_version }}*
              - containerd.io
            state: present
      when: ansible_distribution == 'Rocky'
      tags: [docker, install]
  tags: [docker, install]

# ======================
# Configuration Section 
# ======================
- name: Configure Docker environment
  block:
    - name: Ensure Docker config directory exists
      file:
        path: "{{ docker_config_dir | default('/etc/docker') }}"
        state: directory
        mode: 0755

    - name: Deploy Docker configuration
      template:
        src: config.yml.j2
        dest: "{{ docker_config_file | default('/etc/docker/daemon.json') }}"
        owner: root
        group: root
        mode: 0644
      notify: Restart Docker

    - name: Validate Docker configuration syntax
      command: docker config validate {{ docker_config_file }}
      register: docker_validate
      changed_when: false
      failed_when: docker_validate.rc != 0
      tags: validation

    - name: Test Docker daemon startup (dry-run)
      command: dockerd --validate --config-file={{ docker_config_file }}
      register: docker_dryrun
      changed_when: false
      when: not ansible_check_mode
      tags: validation

    - name: Backup existing config (if any)
      copy:
        src: "{{ docker_config_file | default('/etc/docker/daemon.json') }}"
        dest: "{{ docker_config_file | default('/etc/docker/daemon.json') }}.bak"
        remote_src: yes
      when:
        - not ansible_check_mode
        - (docker_config_file | default('/etc/docker/daemon.json')) is file
      tags: backup
  tags: [docker, config]

# ======================
# Service Management
# ======================
- name: Ensure Docker is running
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes
  tags: [docker, service]

# ======================
# Validation
# ======================
- name: Verify Docker installation
  command: docker --version
  register: docker_version_check
  changed_when: false
  tags: [docker, validate]

# ======================
# NVIDIA Configuration
# ======================
- name: Configure NVIDIA runtime (if enabled)
  block:
    - name: Install NVIDIA container toolkit
      package:
        name: nvidia-container-toolkit
        state: present
      when: docker_nvidia_enabled | bool

    - name: Configure NVIDIA runtime
      template:
        src: nvidia-daemon.json.j2
        dest: /etc/docker/daemon.json
        mode: 0644
      notify: Restart Docker
      when: docker_nvidia_enabled | bool
  when: docker_nvidia_enabled | bool
  tags: [docker, nvidia]
