# host_vars/gpu-node.yml
docker_storage_opts:
  - "dm.basesize=20G"
  - "dm.mkfsarg=-b 4096"

# group_vars/gpu-nodes.yml
# nvidia_driver_version: "470"  # For older GPU architectures
nvidia_device_plugin:
  image: "nvcr.io/nvidia/k8s-device-plugin:v0.12.3"